<?php require_once('app/views/plantilla.phtml') ?>
    <div class="row mt-2">
      <div class="col-md-12 col-lg-7">
        <!-- Card no asignadas -->
        <div class="card border border-primary my-2">
          <div class="card-header bg-primary text-light p-1">
            <h5 class="d-inline-block"><i class="fas fa-list-alt"></i> No Asignadas <span class="badge badge-secondary"><small>1-6 / 1000</small></span></h5>
            <a class="card-link text-light float-right ml-4 mr-1" data-toggle="collapse" href="#noAsign"><i class="fas fa-angle-down collapseCard"></i><i class="fas fa-angle-up collapseCard d-none"></i></a>
            <a href="<?php base_url() ?>incidence/listar/no-asignadas" class="btn btn-light text-dark btn-sm float-right">Ver incidencias</a>
          </div>
          <div id="noAsign" class="collapse show" data-parent="#accordion">
            <div class="card-body p-0">
                <table class="table table-striped table-sm table-bordered m-0">
                <tbody>
                <?php if(!empty($values['noAsign'])){ ?>
                <?php foreach ($values['noAsign'] as $inci) {        ?>
                    <tr>
                        <td width="10%">
                          <a href="<?= base_url()?>incidence/show/<?= $inci->id ?>"><?= sprintf("%03d",$inci->id) ?></a>
                          <br>
                          <?= $inci->estado->cod?> <?= $inci->prioridad->cod ?> Arc
                        </td>
                        <td width="90%">
                          <a href="<?= base_url()?>incidence/show/<?= $inci->id ?>"><?= $inci->asunto ?></a>
                          <br>
                          <small><?= $inci->categoria->nombre ?> - <?= $inci->fechacreacion ?></small>
                        </td>
                    </tr>
                <?php } }else{ ?> 
                <div class="m-4"></div>
                    <?php } ?>
                </tbody>
              </table>
            </div>
            </div>
          </div>
        <!-- Card reportadas por mi -->
        <div class="card border border-primary my-3">
          <div class="card-header bg-primary text-light p-1">
            <h5 class="d-inline-block"><i class="fas fa-list-alt"></i> Reportadas por mí <span class="badge badge-secondary"><small>1-6 / 1000</small></span></h5>
            <a class="card-link text-light float-right ml-4 mr-1" data-toggle="collapse" href="#reportMi"><i class="fas fa-angle-down collapseCard"></i><i class="fas fa-angle-up collapseCard d-none"></i></a>
            <a href="<?php base_url() ?>incidence/listar/reportadas" class="btn btn-light text-dark btn-sm float-right">Ver incidencias</a>
          </div>
          <div id="reportMi" class="collapse" data-parent="#accordion">
            <div class="card-body p-0">
                <table class="table table-striped table-sm table-bordered m-0">
                <tbody>
                <?php if(!empty($values['repMi'])){ ?>
                <?php foreach ($values['repMi'] as $inci) {        ?>
                    <tr>
                        <td width="10%">
                          <a href="<?= base_url()?>incidence/show/<?= $inci->id ?>"><?= sprintf("%03d",$inci->id) ?></a>
                          <br>
                          <?= $inci->estado->cod?> <?= $inci->prioridad->cod ?> Arc
                        </td>
                        <td width="90%">
                          <a href="<?= base_url()?>incidence/show/<?= $inci->id ?>"><?= $inci->asunto ?></a>
                          <br>
                          <small><?= $inci->categoria->nombre ?> - <?= $inci->fechacreacion ?></small>
                        </td>
                    </tr>
                <?php } }else{ ?> 
                <div class="m-4"></div>
                    <?php } ?>
                </tbody>
              </table>
            </div>
            </div>
          </div>
        <!-- Card resueltas -->
        <div class="card border border-primary my-3">
          <div class="card-header bg-primary text-light p-1">
            <h5 class="d-inline-block"><i class="fas fa-list-alt"></i> Resueltas <span class="badge badge-secondary"><small>1-6 / 1000</small></span></h5>
            <a class="card-link text-light float-right ml-4 mr-1" data-toggle="collapse" href="#result"><i class="fas fa-angle-down collapseCard"></i><i class="fas fa-angle-up collapseCard d-none"></i></a>
            <a href="<?php base_url() ?>incidence/listar/resueltas" class="btn btn-light text-dark btn-sm float-right">Ver incidencias</a>
          </div>
          <div id="result" class="collapse show" data-parent="#accordion">
            <div class="card-body p-0">
                <table class="table table-striped table-sm table-bordered m-0">
                <tbody>
                <?php if(!empty($values['reslt'])){ ?>
                <?php foreach ($values['reslt'] as $inci) {        ?>
                    <tr>
                        <td width="10%">
                          <a href="<?= base_url()?>incidence/show/<?= $inci->id ?>"><?= sprintf("%03d",$inci->id) ?></a>
                          <br>
                          <?= $inci->estado->cod?> <?= $inci->prioridad->cod ?> Arc
                        </td>
                        <td width="90%">
                          <a href="<?= base_url()?>incidence/show/<?= $inci->id ?>"><?= $inci->asunto ?></a>
                          <br>
                          <small><?= $inci->categoria->nombre ?> - <?= $inci->fechacreacion ?></small>
                        </td>
                    </tr>
                <?php } }else{ ?> 
                <div class="m-4"></div>
                    <?php } ?>
                </tbody>
              </table>
            </div>
            </div>
          </div>
          <!-- Card Modificadas recientemente -->
          <div class="card border border-primary my-3">
            <div class="card-header bg-primary text-light p-1">
              <h5 class="d-inline-block"><i class="fas fa-list-alt"></i> Modificadas recientemente (5 días) <span class="badge badge-secondary"><small>1-6 / 1000</small></span></h5>
              <a class="card-link text-light float-right ml-4 mr-1" data-toggle="collapse" href="#modifRec"><i class="fas fa-angle-down collapseCard"></i><i class="fas fa-angle-up collapseCard d-none"></i></a>
              <a href="<?php base_url() ?>incidence/listar/modificadas-recientemente" class="btn btn-light text-dark btn-sm float-right">Ver incidencias</a>
            </div>
            <div id="modifRec" class="collapse show" data-parent="#accordion">
            <div class="card-body p-0">
                <table class="table table-striped table-sm table-bordered m-0">
                <tbody>
                <?php if(!empty($values['modif'])){ ?>
                <?php foreach ($values['modif'] as $inci) {        ?>
                    <tr>
                        <td width="10%">
                          <a href="<?= base_url()?>incidence/show/<?= $inci->id ?>"><?= sprintf("%03d",$inci->id) ?></a>
                          <br>
                          <?= $inci->estado->cod?> <?= $inci->prioridad->cod ?> Arc
                        </td>
                        <td width="90%">
                          <a href="<?= base_url()?>incidence/show/<?= $inci->id ?>"><?= $inci->asunto ?></a>
                          <br>
                          <small><?= $inci->categoria->nombre ?> - <?= $inci->fechacreacion ?></small>
                        </td>
                    </tr>
                <?php } }else{ ?> 
                <div class="m-4"></div>
                    <?php } ?>
                </tbody>
              </table>
            </div>
              </div>
            </div>
        <!-- Card asignadas a mi -->
        <div class="card border border-primary my-3">
          <div class="card-header bg-primary text-light p-1">
            <h5 class="d-inline-block"><i class="fas fa-list-alt"></i> Asignadas a mí <span class="badge badge-secondary"><small>1-6 / 1000</small></span></h5>
            <a class="card-link text-light float-right ml-4 mr-1" data-toggle="collapse" href="#asignMi"><i class="fas fa-angle-down collapseCard"></i><i class="fas fa-angle-up collapseCard d-none"></i></a>
            <a href="<?php base_url() ?>incidence/listar/asignadas" class="btn btn-light text-dark btn-sm float-right">Ver incidencias</a>
          </div>
          <div id="asignMi" class="collapse show" data-parent="#accordion">
            <div class="card-body p-0">
                <table class="table table-striped table-sm table-bordered m-0">
                <tbody>
                <?php if(!empty($values['asignMi'])){ ?>
                <?php foreach ($values['asignMi'] as $inci) {        ?>
                    <tr>
                        <td width="10%">
                          <a href="<?= base_url()?>incidence/show/<?= $inci->id ?>"><?= sprintf("%03d",$inci->id) ?></a>
                          <br>
                          <?= $inci->estado->cod?> <?= $inci->prioridad->cod ?> Arc
                        </td>
                        <td width="90%">
                          <a href="<?= base_url()?>incidence/show/<?= $inci->id ?>"><?= $inci->asunto ?></a>
                          <br>
                          <small><?= $inci->categoria->nombre ?> - <?= $inci->fechacreacion ?></small>
                        </td>
                    </tr>
                <?php } }else{ ?> 
                <div class="m-4"></div>
                    <?php } ?>
                </tbody>
              </table>
            </div>
            </div>
          </div>
        </div>

        <div class="col-md-12 col-lg-5">
          <div class="card border border-primary mt-2">
            <div class="card-header bg-primary text-light p-1 ">
              <h5 class="d-inline-block"><i class="far fa-clock"></i> Línea de tiempo <span class="badge badge-secondary"><small>1-6 / 1000</small></span></h5>
              <a class="card-link text-light float-right ml-4 mr-1" data-toggle="collapse" href="#linTiempo"><i class="fas fa-angle-down collapseCard"></i><i class="fas fa-angle-up collapseCard d-none"></i></a>
            </div>
            <div id="linTiempo" class="collapse show" data-parent="#accordion">
            <div class="card-body p-0">
                <table class="table table-striped table-sm table-bordered m-0">
                <tbody>
                <?php if(!empty($values['modif'])){ ?>
                <?php foreach ($values['modif'] as $inci) {        ?>
                    <tr>
                        <td width="10%">
                          <a href="<?= base_url()?>incidence/show/<?= $inci->id ?>"><?= $inci->id ?></a>
                          <br>
                          <?= $inci->prioridad->nombre ?>  <?= $inci->estado->nombre ?> Arc
                        </td>
                        <td width="90%">
                          <a href="<?= base_url()?>incidence/show/<?= $inci->id ?>"><?= $inci->asunto ?></a>
                          <br>
                          <small><?= $inci->categoria->nombre ?> - <?= $inci->fechacreacion ?></small>
                        </td>
                    </tr>
                <?php } }else{ ?> 
                <div class="m-4"></div>
                    <?php } ?>
                </tbody>
              </table>
            </div>
              </div>
            </div>
        </div>
      </div>
    </div>
</body>
</html>
