<?php require_once('plantilla.html'); ?>

<div class="card border border-primary my-3">
  <div class="card-header bg-primary text-light p-1">
    <h5 class="d-inline-block"><i class="fas fa-bars mx-2"></i> Ver detalles de la incidencia <span class="badge badge-secondary"><small>1-6 / 1000</small></span></h5>
  </div>
  <div class="card-body p-0">
      <table class="table table-sm table-bordered m-0">
      <tbody>
        <tr>
          <th scope="col" class="table-info">ID</th>
          <th scope="col" class="table-info">Categoría</th>
          <th scope="col" class="table-info">Fecha de creación</i></th>
          <th scope="col" class="table-info">Última modificación</i></th>
        </tr>
        <tr class="">
          <td>000025</td>
          <td>Administración</td>
          <td>12-01-2018 14:52</td>
          <td>12-01-2018 14:52</td>
        </tr>
        <tr class="spacer"></tr>
        <tr>
          <th class="table-info">Informador</th>
          <td>Paquito</td>
          <th class="table-info">Asignada a</th>
          <td>Eneko</td>
        </tr>
        <tr>
          <th class="table-info">Prioridad</th>
          <td>Normal</td>
          <th class="table-info">Estado</th>
          <td>nueva</td>
        </tr>
        <tr>
          <th class="table-info">Resolución</th>
          <td>abierta</td>
          <td colspan="2"></td>
        </tr>
        <tr class="spacer"></tr>
        <tr>
          <th class="table-info">Resumen</th>
          <td colspan="3"> Esto es el resumen y yo que se que poner</td>
        </tr>
        <tr>
          <th class="table-info">Descripción</th>
          <td colspan="3">Esto es la pedazo de descripcion que vamos puedes poner aqui lo que te de la gana porque cabe lo bueno es eso que cabe y bueno no se que mas poner aunque al escribir eso ya estoy poniendo algo pero buena que me voy ya venga chao.</td>
        </tr>
        <tr class="spacer"></tr>
      </tbody>
    </table>
  </div>
</div>


    <!-- Añadir comentario -->
    <div class="card border border-primary my-2">
      <div class="card-header bg-primary text-light p-1">
        <h5 class="d-inline-block"><i class="fas fa-comment mx-2"></i> Añadir comentario</h5>
        <a class="card-link text-light float-right ml-4 mr-1" data-toggle="collapse" href="#noAsign"><i class="fas fa-angle-down collapseCard"></i><i class="fas fa-angle-up collapseCard d-none"></i></a>
      </div>
      <div id="noAsign" class="collapse show" data-parent="#accordion">
        <form class="" action="index.html" method="post">
        <div class="card-body p-0">
            <table class="table table-sm table-bordered m-0">
            <tbody>
                <tr>
                    <th scope="row" class="table-info">Comentario</th>
                    <td><textarea id="txtComent" name="coment" rows="8" cols="142"></textarea></td>
                </tr>
                <tr>
                    <th scope="row" class="table-info">Subir archivos</th>
                    <td></td>
                </tr>
            </tbody>
          </table>
          <div class="card-header">
            <button type="button" class="btn btn-light text-primary border-primary" name="button">Añadir comentario</button>
          </div>
        </div>
      </form>
        </div>
      </div>

      <!-- Linea de tiempo -->
      <div class="card border border-primary my-3">
        <div class="card-header bg-primary text-light p-1">
          <h5 class="d-inline-block"><i class="fas fa-list-alt mx-2"></i> Mostrando incidencias <span class="badge badge-secondary"><small>1-6 / 1000</small></span></h5>
        </div>
        <div class="card-body p-0">
            <table class="table table-striped table-sm table-bordered m-0 lTime">
            <thead>
              <tr class="table-secondary">
                <th scope="col">Fecha de modificación</th>
                <th scope="col">Nombre de usuario</th>
                <th scope="col">Campo</th>
                <th scope="col">Cambio</th>
              </tr>
            </thead>
            <tbody>
              <tr class="">
                <td>2017-01-12 06:38</td>
                <td>eneko19</td>
                <td>Nueva incidencia</td>
                <td>1</td>
              </tr>

              <tr class="spacer"></tr>
            </tbody>
          </table>
        </div>
      </div>

</div>
