<?php require_once('plantilla.phtml'); ?>

<div class="card border border-primary my-3">
    <div class="card-header bg-primary text-light p-1">
        <h5 class="d-inline-block"><i class="fas fa-bars mx-2"></i> Ver detalles de la incidencia <span class="badge badge-secondary"><small>1-6 / 1000</small></span></h5>
    </div>
    <div class="card-body p-0">
        <table class="table table-sm table-bordered m-0">
            <tbody>
                <tr>
                    <th scope="col" class="table-info">ID</th>
                    <th scope="col" class="table-info">Categoría</th>
                    <th scope="col" class="table-info">Fecha de creación</i></th>
                    <th scope="col" class="table-info">Última modificación</i></th>
                </tr>
                <tr class="">
                    <td><?= sprintf("%05d", $values['incidencia']->id) ?></td>
                    <td><?= $values['incidencia']->categoria->nombre ?></td>
                    <td><?= $values['incidencia']->fechacreacion ?></td>
                    <td><?= $values['incidencia']->fechamodificacion ?></td>
                </tr>
                <tr class="spacer"></tr>
                <tr>
                    <th class="table-info">Informador</th>
                    <td><?= $values['incidencia']->usuarioCreacion->nombre ?></td>
                    <th class="table-info">Asignada a</th>
                    <td><?= $asign = !isset($values['incidencia']->usuarioAsignado->nombre) ? 'sin asignar' : $values['incidencia']->usuarioAsignado->nombre; ?></td>
                </tr>
                <tr>
                    <th class="table-info">Prioridad</th>
                    <td><?= $values['incidencia']->prioridad->cod ?> <?= $values['incidencia']->prioridad->nombre ?></td>
                    <th class="table-info">Estado</th>
                    <td><?= $values['incidencia']->estado->cod ?> <?= $values['incidencia']->estado->nombre ?></td>
                </tr>
                <tr>
                    <th class="table-info">Resolución</th>
                    <td>abierta</td>
                    <td colspan="2"></td>
                </tr>
                <tr class="spacer"></tr>
                <tr>
                    <th class="table-info">Resumen</th>
                    <td colspan="3"> <?= $values['incidencia']->asunto ?></td>
                </tr>
                <tr>
                    <th class="table-info">Descripción</th>
                    <td colspan="3"><?= $values['incidencia']->descripcion ?></td>
                </tr>
                <tr class="spacer"></tr>
            </tbody>
        </table>
    </div>
</div>

<!-- Vista de comentarios-->
<div class="card border border-primary my-2">
    <div class="card-header bg-primary text-light p-1">
        <h5 class="d-inline-block"><i class="fas fa-comments mx-2"></i> Actividades</h5>
        <a class="card-link text-light float-right ml-4 mr-1" data-toggle="collapse" href="#viewComent"><i class="fas fa-angle-down collapseCard"></i><i class="fas fa-angle-up collapseCard d-none"></i></a>
    </div>
    <div id="viewComent" class="collapse show" data-parent="#accordion">
        <div class="card-body p-0">
            <table class="table table-sm table-bordered m-0">
                <tbody>
                    <?php if(!empty($values['comentario'])){ ?>
                <?php foreach ($values['comentario'] as $com) {        ?>
                    <tr class="row m-0 mb-1">
                        <td scope="" class="table-info col-3">
                            <div class="float-left">
                                <img class="img-thumbnail rounded" src="img/logi.png" alt="usuario" width="100" height="100">
                            </div>
                            <div class="">
                                <small><i class="fas fa-user ml-2"></i> <?= $com->usuario->nombre ?></small><br>
                                <small><i class="far fa-clock ml-2"></i> <?= $com->fechacreacion ?></small><br>
                                <small class="ml-2"> <?= $com->usuario->tipousuario->nombre ?></small>
                            </div>
                        </td>

                        <td class="col-9 table-secondary"> <?= $com->descripcion ?> </td>
                    </tr>
                <?php } }else{ ?> 
                <div class="m-4"></div>
                    <?php } ?>
                </tbody>
            </table>
        </div>
    </div>
</div>


<!-- Añadir comentario -->
<div class="card border border-primary my-2">
    <div class="card-header bg-primary text-light p-1">
        <h5 class="d-inline-block"><i class="fas fa-comment mx-2"></i> Añadir comentario</h5>
        <a class="card-link text-light float-right ml-4 mr-1" data-toggle="collapse" href="#addComent"><i class="fas fa-angle-down collapseCard"></i><i class="fas fa-angle-up collapseCard d-none"></i></a>
    </div>
    <div id="addComent" class="collapse show" data-parent="#accordion">
        <form class="" action="<?= base_url() ?>comentario/add/<?= $values['incidencia']->id?>/<?= $values['usuario']->id?>" method="post">
            <div class="card-body p-0">
                <table class="table table-sm table-bordered m-0">
                    <tbody>
                        <tr>
                            <th scope="row" class="table-info">Comentario</th>
                            <td><textarea class="content" name="desc"></textarea></td>
                            
                        </tr>
                        <tr>
                            <th scope="row" class="table-info">Subir archivos</th>
                            <td><input class="" type="file" name="file"></td>
                        </tr>
                    </tbody>
                </table>
                <div class="card-header">
                    <button type="submit" class="btn btn-light text-primary border-primary" name="button">Añadir comentario</button>
                </div>
            </div>
        </form>
    </div>
</div>

<!-- Linea de tiempo -->
<div class="card border border-primary my-3">
    <div class="card-header bg-primary text-light p-1">
        <h5 class="d-inline-block"><i class="fas fa-list-alt mx-2"></i> Mostrando incidencias <span class="badge badge-secondary"><small>1-6 / 1000</small></span></h5>
    </div>
    <div class="card-body p-0">
        <table class="table table-striped table-sm table-bordered m-0 lTime">
            <thead>
                <tr class="table-secondary">
                    <th scope="col">Fecha de modificación</th>
                    <th scope="col">Nombre de usuario</th>
                    <th scope="col">Campo</th>
                    <th scope="col">Cambio</th>
                </tr>
            </thead>
            <tbody>
                <tr class="">
                    <td>2017-01-12 06:38</td>
                    <td>eneko19</td>
                    <td>Nueva incidencia</td>
                    <td>1</td>
                </tr>

                <tr class="spacer"></tr>
            </tbody>
        </table>
    </div>
</div>

</div>
