<?php require_once('plantilla.html'); ?>
                <div class="card border-primary mt-3 mr-3">
                    <h5 class="card-header bg-primary text-light"><i class="fas fa-edit mr-2"></i>Escribe los detalles de la incidencia</h5>
                    <div class="card-body p-0">
                        <table class="table table-striped table-bordered m-0">
                            <form method="POST" action="">
                                <tbody>
                                    <tr>
                                        <th scope="row">Categoría</th>
                                        <td>
                                            <select id="categoria" class="form-control">
                                                <option selected>(seleccionar)</option>
                                                <option>Esta es una</option>
                                                <option>Esta otra xd</option>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Prioridad</th>
                                        <td>
                                            <select id="prioridad" class="form-control">
                                                <option selected>menor</option>
                                                <option>mayor</option>
                                                <option>xededed</option>
                                            </select>
                                        </td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Resumen</th>
                                        <td><input type="text" class="form-control" id="asunto"></td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Descripción</th>
                                        <td><textarea class="form-control" rows="6" id="description"></textarea></td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Subir archivo</th>
                                        <td><input type="email" class="form-control" id="email" placeholder="correo@correo.com"></td>
                                    </tr>
                                </tbody>
                            </form>
                        </table>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-light border-primary">Enviar incidencia</button>
                    </div>
    </div>
    </div>
</body>
</html>
