<?php require_once('app/views/plantilla.phtml'); ?>

    <div class="row container-fluid p-0">

      <div class="col-12">
        <div class="card border border-primary my-3">
          <div class="card-header bg-primary text-light p-1">
            <h5 class="d-inline-block"><i class="fas fa-filter mx-2"></i> Filtros </h5>
            <a class="card-link text-light float-right ml-4 mr-1" data-toggle="collapse" href="#filters"><i class="fas fa-angle-down collapseCard"></i><i class="fas fa-angle-up collapseCard d-none"></i></a>
          </div>
          <div id="filters" class="collapse" data-parent="#accordion">
            <div class="card-body">
              <h1> Filtros </h1>
              <p>Filtros</p>
            </div>
          </div>
          <div class="bg-light p-2">
            <form class="row" action="index.html" method="post">
              <div class="form-group col-4 m-0">
                <input class="form-control form-control-sm" id="formFilter" type="text">
              </div>
              <a href="#" class="btn btn-sm border-primary"> Filtrar</a>
            </form>
          </div>
        </div>
      </div>

      <div class="col-12">
        <div class="card border border-primary my-3">
          <div class="card-header bg-primary text-light p-1">
            <h5 class="d-inline-block"><i class="fas fa-list-alt mx-2"></i> Mostrando incidencias <span class="badge badge-secondary"><small>1-6 / 1000</small></span></h5>
          </div>
          <div class="card-body px-2">
              <table id="example" class="table table-striped table-sm table-bordered m-0">
              <thead>
                <tr class="table-secondary text-center">
                  <th scope="col">ID</th>
                  <th scope="col">P</th>
                  <th scope="col"><i class="fas fa-comment"></i></th>
                  <th scope="col"><i class="fas fa-paperclip"></i></th>
                  <th scope="col">Categoría</th>
                  <th scope="col">Estado</th>
                  <th scope="col">Actualizada</th>
                  <th scope="col" class="text-left">Resumen</th>
                </tr>
              </thead>
              <tbody>
                <tr class="text-center">
                  <td><a href="#">000025</a></td>
                  <td>Alta</td>
                  <td>2</td>
                  <td>1</td>
                  <td>Administración</td>
                  <td>nueva</td>
                  <td>18-04-2018</td>
                  <td class="text-left">Esto es un resumen de una incidencia y solo escribo para ver como se ve</td>
                </tr>
                <tr>
                  <td>000026</td>
                  <td>Baja</td>
                  <td>0</td>
                  <td>1</td>
                  <td>Sistemas</td>
                  <td>confirmada</td>
                  <td>24-04-2018</td>
                  <td>Esto es un resumen de una incidencia y solo escribo para ver como se ve</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </div>

  </div>
