<!DOCTYPE html>
<html>

    <head>
        <meta charset="utf-8">
        <title>Home</title>
        <base href="<?= base_url() ?>">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" >
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/all.js"></script>
        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/jq-3.2.1/dt-1.10.16/datatables.min.css"/>
        <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/jq-3.2.1/dt-1.10.16/datatables.min.js"></script>
        <link rel="stylesheet" href="css/home.css">
        <script type="text/javascript" src="js/scripts.js"></script>
        <script type="text/javascript" src="jquery.dataTables.js"></script>
        <link rel="stylesheet" href="css/richtext.min.css">
        <script src="js/jquery.richtext.js"></script>
    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-global fixed-top p-1">
            <div class="container-fluid navbar navbar-expand-md navbar-light sticky-top">
                <a class="navbar-brand mr-4" href="<?= base_url() ?>">
                    <img src="img/logi.png" width="30" height="30" class="d-inline-block align-top" alt="">
                    <span class="text-light">LooK</span>
                </a>

                <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon "></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!--mxauto -->
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item mr-3">
                            <a href="<?= base_url() ?>incidence/add" class="btn btn-primary btn-sm">Reportar incidencia</a>
                        </li>
                        <li class="nav-item text-right mr-3">
                            <a class="nav-link dropdown-toggle text-light bg-secondary" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <?= $values['usuario']->usuario ?>
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="<?= base_url() ?>login/view"><i class="fas fa-user mr-3"></i>Mi cuenta</a>
                                <?php if($values['usuario']->id_tipousuario == 1){ ?>
                                <a class="dropdown-item" href="<?= base_url() ?>settings"><i class="fas fa-cog mr-3"></i>Administración</a>
                                <?php } ?>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="<?= base_url() ?>login/logout"><i class="fas fa-sign-out-alt mr-3"></i>Salir</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <nav class="navbar-primary border-right border-primary">
        <ul class="navbar-primary-menu">
            <li>
                <a href="<?= base_url() ?>"><i class="fas fa-eye"></i><br><span class="nav-label">Mi vista</span></a>
                <a href="<?= base_url() ?>incidence/listar"><i class="far fa-list-alt"></i><br><span class="nav-label">Ver incidencias</span></a>
                <a href="<?= base_url() ?>incidence/add"><i class="far fa-edit"></i><br><span class="nav-label">Reportar incidencia</span></a>
                <a class="disabled"><i class="fas fa-book"></i><br><span class="nav-label">Wiki</span></a>
                <a class="disabled"><i class="fas fa-cog"></i><br><span class="nav-label">Resumen</span></a>
                <a class="btn-expand-collapse p-0"><i class="fas fa-chevron-circle-left clickExp"></i><i class="fas fa-chevron-circle-right clickExp d-none"></i></a>
            </li>
        </ul>
    </nav>
    <div class="main-content">
        <div class="row bg-info p-2 mr-1 rounded"><?php $_SESSION['iduser'] = $values['usuario']->id; ?>
            <p class="m-0 mt-1"> <i class="fas fa-user mx-1"></i> <small><a href="<?= base_url() ?>login/view"><?= $values['usuario']->usuario ?> ( <?= $values['usuario']->nombre ?> )</a> - <?= $values['usuario']->tipousuario->nombre ?></small></p><!--<?= $values['username'] ?> ( <?= $values['user'] ?> - <?= $values['usertype'] ?>)-->
            <form class="ml-auto" action="<?= base_url() ?>incidence/search" method="POST">
                <div class="input-group mb-0">
                    <div class="input-group-prepend">
                        <span class="input-group-text bg-primary text-white"><i class="fas fa-search"></i></span>
                    </div>
                    <input type="text" class="form-control-sm" id="idInci" name="idInci" placeholder="Incidencia #">
                </div>
            </form>
        </div>
