<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>Register</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.9/js/all.js"></script>
  <style media="screen">
    img {
      width: 300px;
      height: 200px;
    }

    .login-container {
      width: 70%;
      margin: auto;
      background-color: #F7F7F7;
      box-shadow: 0px 0px 15px 0px rgba(0, 0, 0, 0.62);
    }

    .register-container {
      width: 70%;
      padding: 10px;
      margin: auto;
      background-color: #393939;
    }

    .register-container a {
      color: #FE9;
    }

    .header {
      line-height: 28px;
      margin-bottom: 16px;
      margin-top: 18px;
      padding-bottom: 4px;
      border-bottom: 1px solid #CCC;
    }
    a.btn{
      width: 150px;
    }
  </style>
</head>

<body>
  <div class="container">
    <div class="logo">
      <img class="img-fluid rounded mx-auto d-block logo" src="../img/logi.png">
    </div>
    <div class="row login-container mt-3 p-4">
      <h5 class="header w-100"><i class="fas fa-pencil-alt mr-2"></i>Registrarse</h5>
      <form class="w-100" action="<?= base_url() ?>login/registerUser" method="post">
        <!-- Username -->
        <div class="col-12 mb-3">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" class="form-control is-valid" name="username" id="validationUsername" placeholder="Nombre de usuario" minlength="3" maxlength="16" required>
            <div class="invalid-feedback">
              Please choose a username.
            </div>
          </div>
        </div>
        <!-- Contraseña -->
        <div class="col-12 mb-3">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-unlock"></i></span>
            </div>
            <input type="password" class="form-control is-valid" name="password" id="validationPassword" placeholder="Contraseña"  minlength="6" maxlength="32" required>
            <div class="invalid-feedback">
              Please choose a password.
            </div>
          </div>
        </div>
        <div class="col-12 mb-3">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-redo"></i></span>
            </div>
            <input type="password" class="form-control is-valid" name="repassword" id="validationRePassword" placeholder="Confirme contraseña" required>
            <div class="invalid-feedback">
              Please choose a repassword.
            </div>
          </div>
        </div>
        <!-- E-mail -->
        <div class="col-12 mb-3">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-envelope"></i></span>
            </div>
            <input type="text" class="form-control is-valid" name="email" id="validationEmail" placeholder="Correo electrónico" required>
            <div class="invalid-feedback">
              Please choose a e-mail.
            </div>
          </div>
        </div>
        <!-- Nombre y apellidos -->
        <div class="col-12 mb-3">
          <div class="input-group">
            <div class="input-group-prepend">
              <span class="input-group-text"><i class="fas fa-user"></i></span>
            </div>
            <input type="text" class="form-control is-valid" name="name" id="validationName" placeholder="Nombre completo" minlength=8 maxlength="32" required>
            <div class="invalid-feedback">
              Please choose a name.
            </div>
          </div>
        </div>

        <button href="#" type="submit" class="btn btn-dark float-right">Registrarse</button>
      </form>
    </div>
    <div class="row register-container">
      <a href="<?= base_url()?>login">Iniciar sesión</a>
    </div>
  </div>
</body>

</html>
