<?php require_once('app/views/plantilla.phtml'); ?>

<ul class="nav nav-tabs mt-3 font-weight-bold" id="myTab" role="tablist">
    <li class="nav-item">
        <a class="nav-link active" id="users-tab" data-toggle="tab" href="#users" role="tab" aria-controls="home" aria-selected="true">Administrar usuarios</a>
    </li>
    <li class="nav-item" disabled="disabled">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#categorias" role="tab" aria-controls="categorias" aria-selected="false">Administrar categorias</a>
    </li>
</ul>
<div class="tab-content mt-2 mr-4 " id="myTabContent">
    <div class="tab-pane fade show active" id="users" role="tabpanel" aria-labelledby="users-tab">
        <div class="card border-primary">
            <h5 class="card-header bg-primary text-light"><i class="fas fa-users mr-2"></i>Editar usuarios</h5>
            <div class="card-body p-0 table-responsive">
                <table class="table table-bordered m-0">
                    <thead class="table-info">
                    <th>Usuario</th>
                    <th>E-mail</th>
                    <th>Nombre completo</th>
                    <th>Fecha de creación</th>
                    <th>Tipo de usuario</th>
                    <th>Borrar</th>
                    </thead>
                    <tbody>
                        <?php foreach ($values['usuarios'] as $user) { ?>
                            <tr>
                                <td class=""><?= $user->usuario ?></td>
                                <td><?= $user->email ?></td>
                                <td><?= $user->nombre ?></td>
                                <td><?= $user->fechacreacion ?></td>
                                <td><?= $user->tipousuario->nombre ?></td>
                                <td width="5%" class="text-center"> <a href="<?= base_url() ?>login/delete/<?= $user->id ?>" class="btn btn-light" onclick = "if (!confirm('¿Quieres borrar al usuario <?= $user->nombre ?>?')) {
                                            return false;
                                        }"><i class="fas fa-trash-alt text-danger"></i></a></td>
                            </tr>
<?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="tab-pane fade" id="categorias" role="tabpanel" aria-labelledby="categorias-tab">
        <div class="card border-primary">
            <h5 class="card-header bg-primary text-light"><i class="fas fa-edit mr-2"></i>Editar categorías</h5>
            <div class="card-body p-0 table-responsive">
                <table class="table table-bordered m-0">
                    <thead class="table-info">
                    <th>Nombre</th>
                    <th>Descripción</th>
                    <th>Borrar</th>
                    </thead>
                    <tbody>
                      <?php foreach ($values['categorias'] as $cat) { ?>
                            <tr>
                                <td><?= $cat->nombre ?></td>
                                <td><?= $cat->descripcion ?></td>
                                <td width="5%" class="text-center"> <a href="<?= base_url() ?>categoria/delete/<?= $cat->id ?>" class="btn btn-light" onclick = "if (!confirm('¿Quieres borrar la categoría <?= $cat->nombre ?>?')) {
                                            return false; }"><i class="fas fa-trash-alt text-danger"></i></a></td>
                            </tr>
                      <?php } ?>
                    </tbody>
                </table>
            </div>
            <div class="card-footer">
                <a href="" class="btn btn-light border-primary" data-toggle="modal" data-target="#addCat">Añadir categoría</a>
            </div>
        </div>
    </div>
</div>

</div>
<!-- Modal -->
<div class="modal fade" id="addCat" tabindex="-1" role="dialog" aria-labelledby="addCat" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Añadir categoria</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form method="POST" action="<?= base_url() ?>categoria/add">
                  <table class="table table-bordered m-0">
                      <tbody>
                          <tr>
                              <th class="table-info" scope="row">Nombre</th>
                              <td>
                                  <input type="text" class="form-control" name="nombre">
                              </td>
                          </tr>
                          <tr>
                              <th class="table-info" scope="row">Descripcion</th>
                              <td>
                                  <input type="text" class="form-control" name="desc">
                              </td>
                          </tr>
                      </tbody>

                  </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
                <button type="submit" class="btn btn-primary">Añadir</button>
            </div>
            </form>
        </div>
    </div>
</div>
</body>
</html>
