<!DOCTYPE html>
<html>
    <head>
        <?php require_once('app/views/plantilla.phtml'); ?>

    <ul class="nav nav-tabs mt-3 font-weight-bold" id="myTab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="user-tab" data-toggle="tab" href="#user" role="tab" aria-controls="home" aria-selected="true">Mi cuenta</a>
        </li>
        <li class="nav-item" disabled="disabled">
            <a class="nav-link disabled" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Preferencias</a>
        </li>
        <li class="nav-item">
            <a class="nav-link disabled" id="contact-tab" data-toggle="tab" href="#contact" role="tab" aria-controls="contact" aria-selected="false">Contactos</a>
        </li>
    </ul>
    <div class="tab-content mt-2 mr-4 " id="myTabContent">
        <div class="tab-pane fade show active" id="user" role="tabpanel" aria-labelledby="user-tab">
            <form method="POST" action="<?= base_url() ?>login/update">
                <div class="card border-primary">
                    <h5 class="card-header bg-primary text-light"><i class="fas fa-user mr-2"></i>Editar cuenta</h5>
                    <div class="card-body p-0">
                        <table class="table table-bordered m-0">
                            <tbody>
                                <tr>
                                    <th width="40%" class="table-info" scope="row">Nombre de usuario</th>
                                    <td>
                                        <?= $values['usuario']->usuario ?>
                                        <input type="text" class="form-control d-none" id="passActual" name="usuario" value="<?= $values['usuario']->usuario ?>">
                                    </td>
                                </tr>
                                <tr>
                                    <th class="table-info" scope="row">Contraseña actual <a id="chgPass" class="btn float-right table-secondary ">Cambiar contraseña</a></th>
                                    <td><input type="text" class="form-control" id="passActual" name="passActual" placeholder="" required></td>
                                </tr>
                                <tr class="chnPass d-none">
                                    <th class="table-info" scope="row">Constraseña nueva</th>
                                    <td><input type="text" class="form-control" id="passNueva" name="passNueva" </td>
                                </tr>
                                <tr class="chnPass d-none">
                                    <th class="table-info" scope="row">Confirmar contraseña</th>
                                    <td><input type="text" class="form-control" id="passNuevaConf" name="passNuevaConf"></td>
                                </tr>
                                <tr>
                                    <th class="table-info" scope="row">Correo electrónico</th>
                                    <td><input type="email" class="form-control" id="email" name="email" value="<?= $values['usuario']->email ?>"></td>
                                </tr>
                                <tr>
                                    <th class="table-info" scope="row">Nombre real</th>
                                    <td><input type="text" class="form-control" id="nombre" name="nombre" value="<?= $values['usuario']->nombre ?>"></td>
                                </tr>
                                <tr>
                                    <th class="table-info" scope="row">Nivel de acceso</th>
                                    <td><?= $values['usuario']->tipousuario->nombre ?></td>
                                </tr>                                
                            </tbody>

                        </table>
                    </div>
                    <div class="card-footer">
                        <button type="submit" class="btn btn-light border-primary">Actualizar usuario</button>
                    </div>
                </div>
            </form>

        </div>
        <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">...</div>
        <div class="tab-pane fade" id="contact" role="tabpanel" aria-labelledby="contact-tab">...</div>
    </div>

</div>
</body>
</html>